"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { useState, useEffect } from "react";
import Spinner from "@/components/spinner";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulate a loading delay
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1000); // Adjust the time as necessary

    return () => clearTimeout(timer);
  }, []);

  if (loading) {
    return (
      <html>
        <body>
          <Spinner />
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
